version: '3.9'

services:
  backend:
    build: ./ai-service
    ports:
      - "5000:5000"
    volumes:
      - ./ai-service:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
